services:
  code-parsing-microservice:
    build: ./code-parsing-microservice
    container_name: code-parsing-service
    ports:
      - "8001:8000"
      - "17000:17000"
    networks:
      - source_commenting_tool_net

  comment-generation-microservice:
    build: ./comment-generation-microservice
    container_name: comment-generation-service
    depends_on:
      - code-parsing-microservice
    ports:
      - "8002:8000"
      - "17001:17001"
    networks:
      - source_commenting_tool_net

  comment-insertion-microservice:
    build: ./comment-insertion-microservice
    container_name: comment-insertion-service
    depends_on:
      - comment-generation-microservice
    ports:
      - "8003:8000"
    networks:
      - source_commenting_tool_net

  web-interface-microservice:
    build: ./web-interface-microservice
    container_name: web-interface-service
    depends_on:
      - comment-insertion-microservice
    ports:
      - "8004:8004"
    networks:
      - source_commenting_tool_net

networks:
  source_commenting_tool_net:
    driver: bridge
