version: '3.8'

services:
  code_parser:
    build: ./code-parsing-microservice
    ports:
      - "8001:8001"
    networks:
      - app-network

  comment_generator:
    build: ./comment-generation-microservice
    ports:
      - "8002:8002"
    networks:
      - app-network

  comment_inserter:
    build: ./comment-insertion-microservice
    ports:
      - "8003:8003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
