version: '3'

services:
  code_parser:
    build:
      context: ./code-parsing-microservice  
      dockerfile: Dockerfile  
    volumes:
      - ./code-parsing-microservice:/app 
    environment:
      - REQUIREMENTS_FILE=requirements.txt
    ports:
      - "8001:8001"
    networks:
      - app-network

  comment_generator:
    build:
      context: ./comment-generation-microservice 
      dockerfile: Dockerfile  
    volumes:
      - ./comment-generation-microservice:/app 
    environment:
      - REQUIREMENTS_FILE=requirements.txt
    ports:
      - "8003:8003"
    networks:
      - app-network

  comment_inserter:
    build:
      context: ./comment-insertion-microservice  
      dockerfile: Dockerfile  
    volumes:
      - ./comment-insertion-microservice:/app 
    environment:
      - REQUIREMENTS_FILE=requirements.txt
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
