version: '3'

services:
  code_parser:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure Dockerfile is named Dockerfile and exists in this directory
    volumes:
      - .:/app
    environment:
      - REQUIREMENTS_FILE=requirements.txt
    ports:
      - "8001:8001"
    networks:
      - app-network

  comment_generator:
    build:
      context: .
      dockerfile: Dockerfile1  # Ensure Dockerfile1 is named Dockerfile1 and exists in this directory
    volumes:
      - .:/app
    environment:
      - REQUIREMENTS_FILE=requirements1.txt
    ports:
      - "8003:8003"
    networks:
      - app-network

  comment_inserter:
    build:
      context: .
      dockerfile: Dockerfile2  # Ensure Dockerfile2 is named Dockerfile2 and exists in this directory
    volumes:
      - .:/app
    environment:
      - REQUIREMENTS_FILE=requirements2.txt
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
